# Generated by Django 2.1.10 on 2019-07-29 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='episodio',
            name='slug',
            field=models.SlugField(default='', editable=False),
        ),
    ]
